core: core/**/*
cli: cli/**/*
report: report/**/*
vendor: vendor/**/*
android: vendor/vendor-android/**/*
gradle-plugin: marathon-gradle-plugin/**/*
sample: sample/**/*
build:
  - '**/*.build.gradle'
  - buildSrc/**/*
  - default-detekt-config.yml
  - .buildsystem/**/*
git:
  - .gitignore
  - CODEOWNERS
workflow:
  - .github/**/*
ide:
  - .idea/**/*
