[versions]
allure-java = "2.28.0"
allure-environment-writer = "1.0.0"
android-gradle-plugin = "8.4.2"
android-tools = "31.0.2"
apache-commons-collections = "4.4"
apache-commons-io = "2.6"
apache-commons-text = "1.3"
axmlparser = "1.0"
detekt = "1.23.6"
dextestparser = "2.3.4"
gson = "2.8.5"
imgscalr = "4.2"
jackson = "2.9.5"
junit5 = "5.10.3"
jsonassert = "1.5.0"
kluent = "1.64"
koin = "2.0.1"
kotlin = "1.9.24"
kotlin-logging = "1.4.9"
kotlinx-coroutines = "1.8.1"
ktor = "2.0.3"
logback = "1.2.3"
marathon = "0.5.4"
mockito = "5.4.0"
slf4j = "1.7.36"
spek = "1.1.5"
testcontainers = "1.15.3"

[libraries]
allure-java-commons = { module = "io.qameta.allure:allure-java-commons", version.ref = "allure-java" }
allure-environment-writer = { module = "com.github.automatedowl:allure-environment-writer", version.ref = "allure-environment-writer" }
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle-plugin" }
android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }
android-tools-ddmlib = { module = "com.android.tools.ddms:ddmlib", version.ref = "android-tools" }
apache-commons-collections = { module = "org.apache.commons:commons-collections4", version.ref = "apache-commons-collections" }
apache-commons-io = { module = "commons-io:commons-io", version.ref = "apache-commons-io" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }
axmlparser = { module = "com.shazam:axmlparser", version.ref = "axmlparser" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
dextestparser = { module = "com.linkedin.dextestparser:parser", version.ref = "dextestparser" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
imgscalr = { module = "org.imgscalr:imgscalr-lib", version.ref = "imgscalr" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlin-logging" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-apache = { module = "io.ktor:ktor-client-apache" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
spek-api = { module = "org.jetbrains.spek:spek-api", version.ref = "spek" }
spek-engine = { module = "org.jetbrains.spek:spek-junit-platform-engine", version.ref = "spek" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
